[project]
name = "user-api-ghibli-role"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bcrypt>=5.0.0",
    "fastapi>=0.117.1",
    "pydantic[email]>=2.11.9",
    "uvicorn>=0.37.0",
]
